---
- name: Template grafana.ini
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_data_dir }}/config/grafana.ini"
    owner: "472"
    mode: '0644'

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_data_dir }}/docker-compose.yml"
    mode: '0644'
